package jumpman.main.logic;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

import javax.swing.JFrame;

import jumpman.main.levels.LevelBuilder;

public class MainForm extends JFrame
{
	/**
	 * Generated by serialver
	 */
	private static final long serialVersionUID = 8054148208416338876L;
	
	private static String level1 = "Level1.txt";

	public MainForm()
	{
		Level level = LevelBuilder.buildLevel(level1);
		add(level);
		
		setTitle("Jump Man");
		setDefaultCloseOperation(EXIT_ON_CLOSE);
		setSize(Game.screenWidth, Game.screenHeight);
		setLocationRelativeTo(null);
		setVisible(true);
		setResizable(false);
	}
	
    public void close() 
    {
        WindowEvent wev = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wev);
    }
}
