package jumpman.main.logic;

import javax.swing.JFrame;

public class MainForm extends JFrame
{
	/**
	 * Generated by serialver
	 */
	private static final long serialVersionUID = 8054148208416338876L;

	public MainForm()
	{
		add(new Level());
		setTitle("Jump Man");
		setDefaultCloseOperation(EXIT_ON_CLOSE);
		setSize(Game.screenWidth, Game.screenHeight);
		setLocationRelativeTo(null);
		setVisible(true);
		setResizable(false);
	}
}
